service: gcb-slack

provider:
  name: google
  runtime: nodejs8
  project: talos-insight
  credentials: ~/.gcp/talos-credentials.json # path must be absolute
  environment:
    SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
    PROJECT_ID: ${self:provider.project}
    GC_SLACK_STATUS: "SUCCESS FAILURE TIMEOUT INTERNAL_ERROR"
plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - "**"
  include:
    - index.js
    - config.json
    - package.json

functions:
  cloudBuildSlackIntegration:
    handler: subscribe
    events:
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: projects/${self:provider.project}/topics/cloud-builds
